// <auto-generated />
using APIWallet.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIWallet.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230628220024_MyMigration")]
    partial class MyMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("APIWallet.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CPF");

                    b.Property<string>("Nascimento")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Nascimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("APIWallet.Domain.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Banco");

                    b.Property<string>("UltimaAtualizacao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UltimaAtualizacao");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserId");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("REAL")
                        .HasColumnName("ValorAtual");

                    b.HasKey("Id");

                    b.ToTable("Wallet", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
